project:
  type: website

website:
  title: "blog on fossil fuels"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kvatsal2000
format:
  html:
    theme: slate
    css: styles.css



